# Generated by Django 4.2.6 on 2023-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beakjoon_nickname',
            field=models.CharField(blank=True, max_length=30, verbose_name='백준 아이디'),
        ),
    ]
