# Generated by Django 4.2.6 on 2023-10-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_beakjoon_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beakjoon_rank',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
