# Generated by Django 4.2.6 on 2023-10-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_beakjoon_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beakjoon_nickname',
            field=models.CharField(blank=True, max_length=30, verbose_name='백준 닉네임'),
        ),
    ]
