# Generated by Django 4.2.6 on 2023-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_beakjoon_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="beakjoon_rank",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
