# Generated by Django 4.2.6 on 2023-10-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("B5", "B5"),
                            ("B4", "B4"),
                            ("B3", "B3"),
                            ("B2", "B2"),
                            ("B1", "B1"),
                            ("S5", "S5"),
                            ("S4", "S4"),
                            ("S3", "S3"),
                            ("S2", "S2"),
                            ("S1", "S1"),
                            ("G5", "G5"),
                            ("G4", "G4"),
                            ("G3", "G3"),
                            ("G2", "G2"),
                            ("G1", "G1"),
                            ("P5", "P5"),
                        ],
                        max_length=7,
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("problem", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_today", models.BooleanField(default=False)),
            ],
        ),
    ]
