# Generated by Django 4.2.6 on 2023-10-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemclass",
            name="ProblemClass_num",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
